output_dir: './outputs'

data:
  data_path: './buffers/data/vavae_f16d32/train_256'
  fid_reference_file: './buffers/refs/in1k256_fid_ref.npz'
  image_size: 256
  num_classes: 1000
  num_workers: 8
  latent_norm: True
  latent_multiplier: 1.0

vae:
  type: 'vavae_f16d32'
  downsample_ratio: 16

model:
  type: ADiT-XL/1
  in_chans: 32

train:
  load_opt: False
  max_steps: 2000000
  global_batch_size: 256
  gradient_accumulation_steps: 1
  global_seed: 0
  log_every: 100
  ckpt_every: 10000
  ckpt_legacy: 100000
  ema_decay: 0.99995

optimizer:
  type: 'AdamW'
  lr: 0.0001
  weight_decay: 0.0
  beta1: 0.9
  beta2: 0.95
  max_grad_norm: 0.1

muon:
  type: NorMuon
  lr: 0.0005
  momentum: 0.95
  beta2: 0.95
  weight_decay: 0.0
  use_polar_express: False

method:
  type: augmented-isd
  transport: Linear
  label_dropout: 0.1
  use_jvp: False
  precfg: 6.0
  cfgrange: [0.0, 0.9]

sample:
  sampling_steps: 2
  per_batch_size: 128
  fid_sample_num: 50000
  demos: [975, 3, 207, 387, 388, 88, 979, 279]
